/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.pais;

import controlador.Controlador;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import modelo.Pais;
import vista.JDialogMensaje;

/**
 *
 * @author Héctor Arnau
 */
public class JFrameBorrarPais extends javax.swing.JFrame {

    private final JFrame padre;
    /**
     * Creates new form JFrameBorrarPais
     */
    public JFrameBorrarPais() {
        initComponents();
         padre=null;
    }
    
    public JFrameBorrarPais(JFrame padre) {
        this.padre=padre;   
        initComponents();
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonBorrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListPaises = new javax.swing.JList();
        jButtonBorrarTodos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Pais");

        jButtonBorrar.setText("Borrar");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        DefaultListModel modelo=new DefaultListModel();
        List<Pais> paises = Controlador.ejecutarConsulta("SELECT p FROM Pais p ORDER BY nombre");
        for (Pais pais:paises){
            modelo.addElement(pais);
        }
        jListPaises.setModel(modelo);
        jScrollPane1.setViewportView(jListPaises);

        jButtonBorrarTodos.setText("Borrar todos");
        jButtonBorrarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonBorrar)
                        .addGap(36, 36, 36)
                        .addComponent(jButtonBorrarTodos)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBorrar)
                    .addComponent(jButtonBorrarTodos))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        // TODO add your handling code here:
      //  Controlador.borrarPais(jTextFieldNombrePais.getText());
        List<Pais> paises=jListPaises.getSelectedValuesList();
        for (Pais pais: paises){
            Controlador.borrarPais(pais);
            }
        
        DefaultListModel modelo=new DefaultListModel();
        paises = Controlador.ejecutarConsulta("SELECT p FROM Pais p ORDER BY nombre");
        for (Pais pais:paises){
            modelo.addElement(pais); 
        }
        jListPaises.setModel(modelo);
    }
        /*
        Pais res=Controlador.getPais(jTextFieldNombrePais.getText());
        if (res==null){
           JDialogMensaje mensaje=new JDialogMensaje(this,true,"El pais que quieres borrar no existe");
           mensaje.setVisible(true);
        }
        else{
            Controlador.borrarPais(res);
            jTextFieldNombrePais.setText("");
            JDialogMensaje mensaje=new JDialogMensaje(this,true,res.getNombre()+" ha sido borrado");
            mensaje.setVisible(true);
        }
        
    }//GEN-LAST:event_jButtonBorrarActionPerformed
*/
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
      // TODO add your handling code here:
 
    }//GEN-LAST:event_formWindowClosed

    private void jButtonBorrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarTodosActionPerformed
       NewOkCancelBorrarPais mensaje=new NewOkCancelBorrarPais(this,true);
       mensaje.setVisible(true);
       if (mensaje.getReturnStatus()==1){
           for (int i=0; i<jListPaises.getModel().getSize();i++){
               Controlador.borrarPais((Pais)jListPaises.getModel().getElementAt(i));
           }
           jListPaises.setModel(new DefaultListModel());
       }
    }//GEN-LAST:event_jButtonBorrarTodosActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        padre.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameBorrarPais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameBorrarPais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameBorrarPais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameBorrarPais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JFrameBorrarPais().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonBorrarTodos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jListPaises;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
