package vista;

import com.arnau.persistencia.hibernate.HibernateUtil;
import org.hibernate.Session;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Héctor Arnau
 */
public class JFramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public JFramePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuOperaciones = new javax.swing.JMenu();
        jMenuItemComprar = new javax.swing.JMenuItem();
        jMenuItemVender = new javax.swing.JMenuItem();
        jMenuItemCrearDB = new javax.swing.JMenuItem();
        jMenuInsertar = new javax.swing.JMenu();
        jMenuItemInsertarPais = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jMenuOperaciones.setText("Operaciones");

        jMenuItemComprar.setText("Comprar");
        jMenuItemComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemComprarActionPerformed(evt);
            }
        });
        jMenuOperaciones.add(jMenuItemComprar);

        jMenuItemVender.setText("Vender");
        jMenuItemVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVenderActionPerformed(evt);
            }
        });
        jMenuOperaciones.add(jMenuItemVender);

        jMenuItemCrearDB.setText("Crear base de datos");
        jMenuItemCrearDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCrearDBActionPerformed(evt);
            }
        });
        jMenuOperaciones.add(jMenuItemCrearDB);

        jMenuBar1.add(jMenuOperaciones);

        jMenuInsertar.setText("Insertar");

        jMenuItemInsertarPais.setText("Pais");
        jMenuItemInsertarPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInsertarPaisActionPerformed(evt);
            }
        });
        jMenuInsertar.add(jMenuItemInsertarPais);

        jMenuBar1.add(jMenuInsertar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 281, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemComprarActionPerformed
        // TODO add your handling code here:
        JFrameComprar comprar=new JFrameComprar();
        comprar.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_jMenuItemComprarActionPerformed

    private void jMenuItemVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVenderActionPerformed
        JFrameEmpresas empresa=new JFrameEmpresas();
        empresa.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_jMenuItemVenderActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        
        HibernateUtil.closeSessionFactory();
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItemInsertarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInsertarPaisActionPerformed
        
        JFramePais pais=new JFramePais();
        pais.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_jMenuItemInsertarPaisActionPerformed

    private void jMenuItemCrearDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCrearDBActionPerformed
        
        try {
             HibernateUtil.openSessionAndBindToThread();
             Session session = HibernateUtil.getSessionFactory().getCurrentSession();
             HibernateUtil.crearBD();
            
         } finally {
             HibernateUtil.closeSessionAndUnbindFromThread();
         }
        
    }//GEN-LAST:event_jMenuItemCrearDBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        //creo la sesion
        HibernateUtil.buildSessionFactory();
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
               VentanaPrincipal.Ventana=new JFramePrincipal();
               VentanaPrincipal.Ventana.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuInsertar;
    private javax.swing.JMenuItem jMenuItemComprar;
    private javax.swing.JMenuItem jMenuItemCrearDB;
    private javax.swing.JMenuItem jMenuItemInsertarPais;
    private javax.swing.JMenuItem jMenuItemVender;
    private javax.swing.JMenu jMenuOperaciones;
    // End of variables declaration//GEN-END:variables
}
