
    alter table Compra 
        drop constraint FK_4htans2da9oy5fkk75h6y9rhr;

    alter table Dividendo 
        drop constraint FK_9adt3ue300c6dr0ilymrib7ht;

    alter table Venta 
        drop constraint FK_8ncl7fv6kj89fds7hade5mxiq;

    drop table Compra if exists;

    drop table Dividendo if exists;

    drop table Empresa if exists;

    drop table Mercado if exists;

    drop table Pais if exists;

    drop table Venta if exists;

    create table Compra (
        Id integer generated by default as identity (start with 1),
        Cantidad integer,
        Fecha date,
        Precio float,
        Empresa integer,
        primary key (Id)
    );

    create table Dividendo (
        Id integer generated by default as identity (start with 1),
        Acciones integer,
        Dinero float,
        Fecha date,
        Empresa integer,
        primary key (Id)
    );

    create table Empresa (
        Id integer generated by default as identity (start with 1),
        Cantidad integer,
        Nombre varchar(255),
        primary key (Id)
    );

    create table Mercado (
        Id integer generated by default as identity (start with 1),
        Nombre varchar(255),
        primary key (Id)
    );

    create table Pais (
        Id integer generated by default as identity (start with 1),
        nombre varchar(255),
        primary key (Id)
    );

    create table Venta (
        Id integer generated by default as identity (start with 1),
        Cantidad integer,
        Fecha date,
        Precio float,
        Empresa integer,
        primary key (Id)
    );

    alter table Empresa 
        add constraint UK_3cro8hs2qk8jcapgf27mulsjv unique (Nombre);

    alter table Mercado 
        add constraint UK_seh2ngnf4osmmorughj3sn84x unique (Nombre);

    alter table Pais 
        add constraint UK_l5qlrewxrm73gfpy7hir4odd3 unique (nombre);

    alter table Compra 
        add constraint FK_4htans2da9oy5fkk75h6y9rhr 
        foreign key (Empresa) 
        references Empresa;

    alter table Dividendo 
        add constraint FK_9adt3ue300c6dr0ilymrib7ht 
        foreign key (Empresa) 
        references Empresa;

    alter table Venta 
        add constraint FK_8ncl7fv6kj89fds7hade5mxiq 
        foreign key (Empresa) 
        references Empresa;
